services:
  # Milvus services
  milvus-etcd:
    image: quay.io/coreos/etcd:v3.5.16
    labels:
      autoheal-label: true
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DATA_DIRPATH}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always

  milvus-minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    labels:
      autoheal-label: true
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-accesskey}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-secretkey}
    ports:
      - "${MINIO_HOST_PORT_9001:-9001}:9001"
      - "${MINIO_HOST_PORT_9000:-9000}:9000"
    volumes:
      - ${DATA_DIRPATH}/volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always

  milvus-standalone:
    image: milvusdb/milvus:v2.5.5
    labels:
      autoheal-label: true
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: milvus-etcd:2379
      MINIO_ADDRESS: milvus-minio:9000
      MINIO_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY:-accesskey}
      MINIO_SECRET_ACCESS_KEY: ${MINIO_SECRET_KEY:-secretkey}
    volumes:
      - ./milvus.yaml:/milvus/configs/milvus.yaml
      - ${DATA_DIRPATH}/volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    restart: always
    ports:
      - "${MILVUS_HOST_PORT_19530:-19530}:19530"
      - "${MILVUS_HOST_PORT_9091:-9091}:9091"
    depends_on:
      milvus-etcd:
        condition: service_healthy
        restart: true
      milvus-minio:
        condition: service_healthy
        restart: true

  # Service for restarting unhealthy containers
  autoheal:
    image: willfarrell/autoheal:1.2.0
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal-label
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # MongoDB service
  mongo:
    image: mongo:8.0.9
    labels:
      autoheal-label: true
    ports:
      - "${MONGO_HOST_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - ${DATA_DIRPATH}/volumes/mongo:/data/db
    restart: always

  # RabbitMQ service
  rabbitmq:
    image: rabbitmq:4.1-management-alpine
    ports:
      - "${RABBITMQ_HOST_PORT_5672:-5672}:5672"
      - "${RABBITMQ_HOST_PORT_15672:-15672}:15672"
    labels:
      autoheal-label: true
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - ${DATA_DIRPATH}/volumes/rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Redis service
  redis:
    image: redis:8.4.0
    ports:
      - "${REDIS_HOST_PORT:-6379}:6379"
    labels:
      autoheal-label: true
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
