apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aiod-enhanced-interaction.ollama.fullname" . }}-pvc
  labels:
    {{- include "aiod-enhanced-interaction.ollama.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass.name }}
  resources:
    requests:
      storage: 30Gi
