{{- if and .Values.use_llm .Values.ollama.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aiod-enhanced-interaction.ollama.fullname" . }}-pvc
  labels:
    {{- include "aiod-enhanced-interaction.ollama.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - {{ .Values.ollama.persistence.accessMode | default "ReadWriteOnce" }}
  storageClassName: {{ .Values.ollama.persistence.storageClass | default .Values.storageClass.name }}
  resources:
    requests:
      storage: {{ .Values.ollama.persistence.size }}
{{- end }}
