{{- if and .Values.app.enabled .Values.app.persistence.model.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aiod-enhanced-interaction.app.fullname" . }}-model-pvc
  labels:
    {{- include "aiod-enhanced-interaction.app.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - {{ .Values.app.persistence.model.accessMode | default "ReadWriteMany" }}
  storageClassName: {{ .Values.app.persistence.model.storageClass | default .Values.storageClass.name }}
  resources:
    requests:
      storage: {{ .Values.app.persistence.model.size }}
{{- end }}

---

{{- if and .Values.app.enabled .Values.app.persistence.coldData.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aiod-enhanced-interaction.app.fullname" . }}-cold-data-pvc
  labels:
    {{- include "aiod-enhanced-interaction.app.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - {{ .Values.app.persistence.coldData.accessMode | default "ReadWriteMany" }}
  storageClassName: {{ .Values.app.persistence.coldData.storageClass | default .Values.storageClass.name }}
  resources:
    requests:
      storage: {{ .Values.app.persistence.coldData.size }}
{{- end }}

---

{{- if and .Values.app.enabled (not .Values.milvus.enabled) .Values.app.persistence.milvusData.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aiod-enhanced-interaction.app.fullname" . }}-milvus-data-pvc
  labels:
    {{- include "aiod-enhanced-interaction.app.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - {{ .Values.app.persistence.milvusData.accessMode | default "ReadWriteMany" }}
  storageClassName: {{ .Values.app.persistence.milvusData.storageClass | default .Values.storageClass.name }}
  resources:
    requests:
      storage: {{ .Values.app.persistence.milvusData.size }}
{{- end }}
