apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aiod-enhanced-interaction.app.fullname" . }}-secret
  labels:
    {{- include "aiod-enhanced-interaction.app.labels" . | nindent 4 }}
type: Opaque
stringData:
  # TODO these credentials should be owned by the Milvus resource
  # Milvus credentials
  milvus-user: "aiod"  # Replace with your Milvus user
  milvus-pass: "changeme"  # Replace with your Milvus password
  milvus-new-root-pass: "changeme"  # Replace with new root password for Milvus

  # Chatbot API key
  CHATBOT__MISTRAL_KEY: "AodGRSVi1zMgcxCAWDBuxrCk3ImRU8yR"

  # Optional: Logfire token
  LOGFIRE_TOKEN: "pylf_v1_eu_WmrbKyzWn5sbz7PQw11W6jd7n1h0pr9SZnRz8HMT0rXR"
