apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aiod-enhanced-interaction.mongo.fullname" . }}-secret
  labels:
    {{- include "aiod-enhanced-interaction.mongo.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ required "secrets.mongo.username is required" .Values.secrets.mongo.username | quote }}
  password: {{ required "secrets.mongo.password is required" .Values.secrets.mongo.password | quote }}
