apiVersion: v1
kind: Service
metadata:
  name: {{ include "aiod-enhanced-interaction.mongo.fullname" . }}-headless
  labels:
    {{- include "aiod-enhanced-interaction.mongo.labels" . | nindent 4 }}
spec:
  clusterIP: None  # Headless service for StatefulSet
  ports:
  - port: {{ .Values.mongo.service.port }}
    targetPort: 27017
    name: mongo
  selector:
    {{- include "aiod-enhanced-interaction.mongo.selectorLabels" . | nindent 4 }}
