{{- if .Values.redis.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aiod-enhanced-interaction.redis.fullname" . }}-pvc
  labels:
    {{- include "aiod-enhanced-interaction.redis.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.redis.persistence.storageClass | default .Values.storageClass.name }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
{{- end }}
