{{- if .Values.dbPopulation.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aiod-enhanced-interaction.fullname" . }}-db-dumps-pvc
  labels:
    {{- include "aiod-enhanced-interaction.labels" . | nindent 4 }}
    app.kubernetes.io/component: db-population
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - {{ .Values.dbPopulation.pvc.accessMode | default "ReadWriteOnce" }}
  storageClassName: {{ .Values.dbPopulation.pvc.storageClass | default .Values.storageClass.name }}
  resources:
    requests:
      storage: {{ .Values.dbPopulation.pvc.size }}
{{- end }}
