apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aiod-enhanced-interaction.rabbitmq.fullname" . }}-secret
  labels:
    {{- include "aiod-enhanced-interaction.rabbitmq.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ required "secrets.rabbitmq.username is required" .Values.secrets.rabbitmq.username | b64enc }}
  password: {{ required "secrets.rabbitmq.password is required" .Values.secrets.rabbitmq.password | b64enc }}
